"""
Scalar documentation renderer implementation following Open/Closed Principle.

This implementation provides Scalar-specific documentation rendering while
following SOLID principles to allow easy extension and substitution.
"""

import json
from html import escape as html_escape
from typing import Any, Dict, List, cast

from ..interfaces.documentation_renderer import DocumentationRenderer


class ScalarDocumentationRenderer(DocumentationRenderer):
    """
    Scalar-specific documentation renderer following Open/Closed Principle.

    This implementation can be extended for custom Scalar configurations
    without modifying the base class, and can be substituted for any
    other DocumentationRenderer implementation (Liskov Substitution Principle).
    """

    def __init__(
        self,
        theme: str = "default",
        layout: str = "modern",
        custom_css: str = "",
        hide_download_button: bool = False,
        search_hotkey: str = "k"
    ):
        """
        Initialize Scalar renderer with configuration options.

        Args:
            theme: Scalar theme name
            layout: Scalar layout style
            custom_css: Custom CSS for styling
            hide_download_button: Whether to hide download button
            search_hotkey: Keyboard shortcut for search
        """
        self.theme = theme
        self.layout = layout
        self.custom_css = custom_css
        self.hide_download_button = hide_download_button
        self.search_hotkey = search_hotkey

    def render_catalog_page(self, contracts: List[Dict[str, Any]]) -> str:
        """
        Render a Scalar catalog page showing multiple API contracts.

        Args:
            contracts: List of contract metadata dictionaries

        Returns:
            HTML string for the Scalar catalog page
        """
        if not contracts:
            return self._render_empty_catalog()

        # Generate Scalar configuration for multiple APIs
        scalar_config = self.get_catalog_config(contracts)

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>API Contract Catalog</title>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style>
                {self._get_catalog_custom_css()}
            </style>
        </head>
        <body>
            <div id="catalog-header">
                <h1>API Contract Catalog</h1>
                <p>Centralized catalog of governed API contracts</p>
            </div>
            <script
                id="api-reference"
                data-configuration='{json.dumps(scalar_config)}'
            ></script>
            <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
        </body>
        </html>
        """

    def render_contract_page(self, contract_url: str, title: str) -> str:
        """
        Render a Scalar documentation page for a single API contract.

        Args:
            contract_url: URL to the OpenAPI specification
            title: Title for the documentation page

        Returns:
            HTML string for the Scalar contract documentation page
        """
        scalar_config = self.get_renderer_config(contract_url)
        safe_title = html_escape(title)
        safe_url = html_escape(contract_url)

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{safe_title}</title>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style>
                {self.custom_css}
            </style>
        </head>
        <body>
            <script
                id="api-reference"
                data-url="{safe_url}"
                data-configuration='{json.dumps(scalar_config)}'
            ></script>
            <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
        </body>
        </html>
        """

    def get_renderer_config(self, contract_url: str) -> Dict[str, Any]:
        """
        Generate Scalar-specific configuration for a single contract.

        Args:
            contract_url: URL to the OpenAPI specification

        Returns:
            Scalar configuration dictionary
        """
        return {
            "theme": self.theme,
            "layout": self.layout,
            "hideDownloadButton": self.hide_download_button,
            "searchHotKey": self.search_hotkey,
            "spec": {
                "url": contract_url
            },
            "customCss": self.custom_css,
            "metaData": {
                "title": "API Documentation",
                "description": "Generated by Contract Stipulations System"
            }
        }

    def get_catalog_config(self, contracts: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Generate Scalar-specific configuration for a multi-API catalog.

        Args:
            contracts: List of contract metadata dictionaries

        Returns:
            Scalar configuration dictionary for catalog display
        """
        # Build API list for Scalar multi-API display
        apis = []
        for contract in contracts:
            api_info = {
                "name": f"{contract.get('title', contract['category'])} ({contract['api_major_version']})",
                "url": contract.get('openapi_url', f"/contracts/{contract['category']}/{contract['api_major_version']}/openapi.json"),
                "description": contract.get('description', ''),
                "category": contract['category'],
                "version": contract['api_major_version']
            }
            apis.append(api_info)

        return {
            "theme": self.theme,
            "layout": self.layout,
            "hideDownloadButton": self.hide_download_button,
            "searchHotKey": self.search_hotkey,
            "apis": apis,
            "customCss": self.custom_css,
            "metaData": {
                "title": "API Contract Catalog",
                "description": "Centralized catalog of governed API contracts"
            }
        }

    def supports_multi_api(self) -> bool:
        """
        Check if Scalar supports displaying multiple APIs in one view.

        Returns:
            True - Scalar supports multi-API display
        """
        return True

    def _render_empty_catalog(self) -> str:
        """Render page for empty catalog."""
        return """
        <!DOCTYPE html>
        <html>
        <head>
            <title>API Contract Catalog</title>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style>
                body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
                .empty-state { color: #666; }
            </style>
        </head>
        <body>
            <div class="empty-state">
                <h1>API Contract Catalog</h1>
                <p>No contracts are currently available in the catalog.</p>
                <p>Contracts will appear here once they are exposed through the stipulations system.</p>
            </div>
        </body>
        </html>
        """

    def _get_catalog_custom_css(self) -> str:
        """Get custom CSS for catalog page."""
        base_css = """
            #catalog-header {
                text-align: center;
                padding: 20px;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                margin-bottom: 20px;
            }

            #catalog-header h1 {
                margin: 0;
                font-size: 2.5em;
                font-weight: 300;
            }

            #catalog-header p {
                margin: 10px 0 0 0;
                opacity: 0.9;
            }

            .scalar-api-reference {
                --scalar-color-1: #2563eb;
                --scalar-color-2: #1e40af;
                --scalar-color-3: #1e3a8a;
            }
        """

        return base_css + "\n" + self.custom_css


class DocumentationRendererRegistry:
    """
    Registry for documentation renderers implementing plugin architecture.

    This allows adding new documentation renderers without modifying
    existing code (Open/Closed Principle).
    """

    def __init__(self):
        """Initialize the renderer registry."""
        self._renderers: Dict[str, type] = {}
        self._default_renderer = "scalar"

        # Register built-in renderers
        self.register_renderer("scalar", ScalarDocumentationRenderer)

    def register_renderer(self, name: str, renderer_class: type) -> None:
        """
        Register a new documentation renderer.

        Args:
            name: Unique name for the renderer
            renderer_class: Class implementing DocumentationRenderer interface
        """
        if not issubclass(renderer_class, DocumentationRenderer):
            raise ValueError("Renderer class must implement DocumentationRenderer interface")

        self._renderers[name] = renderer_class

    def get_renderer(self, name: str, **kwargs) -> DocumentationRenderer:
        """
        Get a documentation renderer instance by name.

        Args:
            name: Name of the renderer
            **kwargs: Configuration arguments for the renderer

        Returns:
            DocumentationRenderer instance

        Raises:
            ValueError: If renderer name is not registered
        """
        if name not in self._renderers:
            raise ValueError(f"Unknown renderer: {name}. Available: {list(self._renderers.keys())}")

        renderer_class = self._renderers[name]
        # Safe: register_renderer() enforces issubclass(renderer_class, DocumentationRenderer)
        return cast(DocumentationRenderer, renderer_class(**kwargs))

    def list_renderers(self) -> List[str]:
        """
        List all registered renderer names.

        Returns:
            List of renderer names
        """
        return list(self._renderers.keys())

    def set_default_renderer(self, name: str) -> None:
        """
        Set the default renderer.

        Args:
            name: Name of the renderer to set as default

        Raises:
            ValueError: If renderer name is not registered
        """
        if name not in self._renderers:
            raise ValueError(f"Cannot set unknown renderer as default: {name}")

        self._default_renderer = name

    def get_default_renderer(self, **kwargs) -> DocumentationRenderer:
        """
        Get the default documentation renderer.

        Args:
            **kwargs: Configuration arguments for the renderer

        Returns:
            Default DocumentationRenderer instance
        """
        return self.get_renderer(self._default_renderer, **kwargs)


# Global registry instance for easy access
documentation_registry = DocumentationRendererRegistry()


class SwaggerUIRenderer(DocumentationRenderer):
    """
    Example alternative renderer for Swagger UI.

    This demonstrates how new renderers can be added following
    the Open/Closed Principle without modifying existing code.
    """

    def __init__(self, theme: str = "default"):
        """Initialize Swagger UI renderer."""
        self.theme = theme

    def render_catalog_page(self, contracts: List[Dict[str, Any]]) -> str:
        """Render Swagger UI catalog page (simplified example)."""
        # This would contain Swagger UI specific implementation
        return """
        <!DOCTYPE html>
        <html>
        <head><title>API Catalog - Swagger UI</title></head>
        <body>
            <div id="swagger-ui"></div>
            <script src="https://unpkg.com/swagger-ui-dist@3.52.5/swagger-ui-bundle.js"></script>
            <script>
                // Swagger UI catalog implementation would go here
            </script>
        </body>
        </html>
        """

    def render_contract_page(self, contract_url: str, title: str) -> str:
        """Render Swagger UI contract page."""
        safe_title = html_escape(title)
        safe_url = html_escape(contract_url)
        return f"""
        <!DOCTYPE html>
        <html>
        <head><title>{safe_title}</title></head>
        <body>
            <div id="swagger-ui"></div>
            <script src="https://unpkg.com/swagger-ui-dist@3.52.5/swagger-ui-bundle.js"></script>
            <script>
                SwaggerUIBundle({{
                    url: '{safe_url}',
                    dom_id: '#swagger-ui',
                    presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.presets.standalone]
                }});
            </script>
        </body>
        </html>
        """

    def get_renderer_config(self, contract_url: str) -> Dict[str, Any]:
        """Get Swagger UI configuration."""
        return {
            "url": contract_url,
            "theme": self.theme
        }

    def get_catalog_config(self, contracts: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Get Swagger UI catalog configuration."""
        return {
            "urls": [
                {
                    "url": contract.get('openapi_url'),
                    "name": f"{contract['category']} {contract['api_major_version']}"
                }
                for contract in contracts
            ]
        }

    def supports_multi_api(self) -> bool:
        """Swagger UI supports multi-API through URL selector."""
        return True


# Register the example alternative renderer
documentation_registry.register_renderer("swagger-ui", SwaggerUIRenderer)
